### ISSUE TITLE
'A curated awesome list of educational resources with focus on RSE by HIFIS' link is broken

### ISSUE THREAD

**Issue by StephanJanosch** [hifis-net/awesome-rse#1]
Section 'A curated awesome list of educational resources with focus on RSE by HIFIS' leads to link

https://github.com/hifis-net/awesome-rse-education

which does not work.

Best,
Stephan

**Comment by tobiashuste** [comment]
Thanks for the hint. The lists are currently about to be created and filled with content. The project is still private and everything is considered to be Work in Progress still.

Can we already set it to public, @Drake81?

**Comment by Drake81** [comment]
The education list needs some refinement before we can publish it. Therefore I'll remove the link temporarily too avoid confusion.

**Comment by Drake81** [comment]
Temporarily removed in commit d841bdb7dda85b2791959c2ce2e84cbb3484b20d
